### ISSUE TITLE
how to load "resume_state"?

### ISSUE THREAD

**Issue by zhengqianisme** [CS-GangXu/TMNet#5]
Dear guys,I want to loading resume state, May I ask you a question about what should i do?
In "config",What is  "resume_state" parameter filled in? thank u!!!

**Comment by CS-GangXu** [comment]
@zhengqianisme Hi! After the training process, there is a .pth file which consists of model parameters and a .state file which consists of the scheduler parameters. You can find these files in the experiment folder:

Thus, you just need to write the corresponding path in the config file:
```
path:
  pretrain_model_G: ***/Epoch_100.pth
  strict_load: true
  resume_state: ***/Epoch_100.state
```
